# Generated by Django 5.1.5 on 2025-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(error_messages='No Image', null=True, upload_to=''),
        ),
    ]
