# Generated by Django 5.1.5 on 2025-02-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sport', 'Sport'), ('Kitchen', 'Kitchen'), ('Beauty', 'Beauty')], max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='Accounts.tag'),
        ),
    ]
