# Generated by Django 5.1.5 on 2025-04-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Email',
        ),
    ]
