# Generated by Django 5.1.5 on 2025-02-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
